apiVersion: v1
kind: Pod
metadata:
  name: nginxwala
spec:
  containers:
    - name: nginxwalacontainer
      image: nginx
      volumeMounts:
         - name: nginxconfigvolume
         - mountPath: /etc/nginx/config.d
  volumes: 
    - name: nginxconfigvolume
      configMap:
         name: nginx.conf